### ISSUE TITLE
ID is different from MasterID

### ISSUE THREAD

**Issue by Ragnnn** [irlndts/go-discogs#33]
Hey there,

Still working with your lib, I'm trying to search an album from an artist like so:
```
disc.Search.Search(discogs.SearchRequest{
        Title:   title,
        Artist:  artist,
        Format:  "album",
        Page:    0,
        PerPage: 100,
    })
```
Which makes a request like this:
```
https://api.discogs.com/database/search?page=0&per_page=500&artist=eminem&format=album&title=Infinite
```

The result of this request gives you a `master_id` that I'd like to use to then get all the tracks in the album. I thought `master_id` was the same as `id`, until this request:
```
https://api.discogs.com/database/search?page=0&per_page=500&artist=Jenifer&format=album&title=declaration
```

If you could add a `MasterID` in your Search structure that'll be great!

Thank you for your time

**Comment by irlndts** [comment]
Hello and thank you again. 
The field wasn't presented in doc's examples so i missed it. 
Now it's just added via #34 

All the best,
Artem.
