### ISSUE TITLE
Missing fields in Artist and Master

### ISSUE THREAD

**Issue by Ragnnn** [irlndts/go-discogs#35]
Hey again,

I saw that the field `name` in the `Artist` structure was missing, just that I'm doing an API and do not have the artist's name when they give me the ID.

I looked for more missing fields as I was at it, here's the list:
```
Artist
    name
    realname
    aliases
Master
    num_for_sale
    most_recent_release
    notes
    most_recent_release_url
    lowest_price
```

Thanks for adding them (specially the artist's name ;))

**Comment by irlndts** [comment]
Hi, 
fields added, and I also rewrote tests a little bit and added some more missed and broken fields
for details have a look at #36 

Cheers
